kasa_samobslugowa: main.cpp bin.cpp managment.cpp interface_functions.cpp employee.cpp luz.cpp product.cpp
	g++ -o kasa_samobslugowa main.cpp bin.cpp managment.cpp interface_functions.cpp employee.cpp luz.cpp product.cpp -I.
